name: Update my Credly badges for my README.md

on:
  schedule:
    # Runs daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual runs

jobs:
  update_my_Credly_badges:
    name: Update my README with my Credly Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Badges
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: ${{ github.actor }} # Uses your GitHub username
          NUMBER_LAST_BADGES: 7 # Show last 4 badges (0 = all)
